version: "3.8"
services:
  vscode:
    image: battleship:latest
    volumes:
      - .:/app:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "db"
 
