on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: pg-secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: "23"
          elixir-version: "1.11.2"
          # see: https://github.com/actions/setup-elixir/issues/49
          experimental-otp: true
      - run: mix deps.get
      - run: npm ci
        working-directory: "./assets"
      - run: mix coveralls.github
      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        with:
          name: 'screenshots'
          path: screenshots
        if: ${{ failure() }}
